#!/bin/bash

COMMIT_MSG_FILE="$1"
FIRST_LINE=$(head -n 1 "$COMMIT_MSG_FILE")

# Validar formato
echo "$FIRST_LINE" | grep -qE "^(feature|fix|docs|test|chore|improve|version):" || {
  echo "Invalid commit message"
  exit 1
}

# Si es docs: no compilar
if [[ "$FIRST_LINE" =~ ^docs: ]]; then
  echo "Documentation commit detected — skipping build"
  exit 0
fi

# Para el resto, ejecutar build
make build_debug || exit 1