#!/bin/bash

COMMIT_MSG_FILE="$1"
FIRST_LINE=$(head -n 1 "$COMMIT_MSG_FILE")

# Validar formato
echo "$FIRST_LINE" | grep -qE "^(feature|fix|docs|test|chore|improve|version|changelog|refactor):" || {
  echo "Invalid commit message"
  echo "Valid prefixes: feature fix docs test chore improve version changelog refactor"
  exit 1
}

# Si es docs: no compilar
if [[ "$FIRST_LINE" =~ ^changelog: ]]; then
  echo "Changelog commit detected — skipping build"
  exit 0
fi