#!/usr/bin/env bash
set -e

if [ "$(git rev-parse --abbrev-ref HEAD)" = "main" ] &&
    grep -R -nP --exclude-dir={build,.git} '//\s*TODO:' RogPerfTuner Framework \
    | sed 's/^\([^:]*:[^:]*\):/  \1\n    /'
then
    echo "❌ Pending TODOs found in code"
    exit 1
fi

# Format code
make format

# Re-add formatted files
FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(cpp|hpp)$' || true)

if [ -n "$FILES" ]; then
    git add $FILES
fi

exit 0