#!/usr/bin/env bash
set -e

# Format code
make format

# Re-add formatted files
FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(cpp|hpp)$' || true)

if [ -n "$FILES" ]; then
    git add $FILES
fi

exit 0