#!/bin/bash
set -e

if [ ! -z "$DEBUG" ] ; then
  env
  set -x
fi

THIS="$0"
# http://stackoverflow.com/questions/3190818/
args=("$@")
NUMBER_OF_ARGS="$#"

if [ -z "$APPDIR" ] ; then
  # Find the AppDir. It is the directory that contains AppRun.
  # This assumes that this script resides inside the AppDir or a subdirectory.
  # If this script is run inside an AppImage, then the AppImage runtime likely has already set $APPDIR
  path="$(dirname "$(readlink -f "${THIS}")")"
  while [[ "$path" != "" && ! -e "$path/$1" ]]; do
    path=${path%/*}
  done
  APPDIR="$path"
fi

export PATH="${APPDIR}:${PATH}"
export RCC_ASSETS_DIR="${APPDIR}/usr/share/rog-perf-tuner"
export LD_LIBRARY_PATH="$APPDIR/usr/lib:$LD_LIBRARY_PATH"

for path in \
    "/usr/lib/qt6/plugins" \
    "/usr/lib64/qt6/plugins" \
    "/usr/lib/x86_64-linux-gnu/qt6/plugins"
do
    if [ -d "$path" ]; then
        case ":$QT_PLUGIN_PATH:" in
            *":$path:"*) ;; 
            *) export QT_PLUGIN_PATH="${QT_PLUGIN_PATH:+$QT_PLUGIN_PATH:}$path" ;;
        esac
        break
    fi
done



BIN="$APPDIR/usr/bin/rog-perf-tuner"

if [ $NUMBER_OF_ARGS -eq 0 ] ; then
    exec "$BIN"
else
    exec "$BIN" "${args[@]}"
fi
