#!/bin/bash
set -e

if [ ! -z "$DEBUG" ] ; then
  env
  set -x
fi

THIS="$0"
args=("$@")
NUMBER_OF_ARGS="$#"

if [ -z "$APPDIR" ] ; then
  path="$(dirname "$(readlink -f "${THIS}")")"
  while [[ "$path" != "" && ! -e "$path/$1" ]]; do
    path=${path%/*}
  done
  APPDIR="$path"
fi

export PATH="${APPDIR}:${PATH}"
export RCC_ASSETS_DIR="${APPDIR}/usr/share/rog-perf-tuner"

BIN="$APPDIR/usr/bin/rog-perf-tuner"

if [ $NUMBER_OF_ARGS -eq 0 ] ; then
    exec "$BIN"
else
    exec "$BIN" "${args[@]}"
fi
