#pragma once

enum class Events : int {
	APPLICATION_STOP,
	UDEV_CLIENT_DEVICE_EVENT,
	HARDWARE_SERVICE_USB_REMOVED,
	HARDWARE_SERVICE_USB_ADDED,
	HARDWARE_SERVICE_ON_BATTERY,
	HARDWARE_SERVICE_THRESHOLD_CHANGED,
	HARDWARE_SERVICE_BOOT_SOUND_CHANGED,
	ORGB_SERVICE_ON_BRIGHTNESS,
	ORGB_SERVICE_ON_EFFECT,
	ORGB_SERVICE_ON_COLOR,
	PROFILE_SERVICE_ON_PROFILE,
	PROFILE_SERVICE_ON_SCHEDULER,
	STEAM_SERVICE_GAME_EVENT,
	APPLICATION_SERVICE_UPDATE_AVAILABLE,
	APPLICATION_SERVICE_UPDATE_START
};