#pragma once

enum class Events : int {
	APPLICATION_SHUTDOWN,
	APPLICATION_STOP,
	UDEV_CLIENT_DEVICE_EVENT,
	HARDWARE_SERVICE_USB_REMOVED,
	HARDWARE_SERVICE_USB_ADDED,
	HARDWARE_SERVICE_ON_BATTERY,
	HARDWARE_SERVICE_THRESHOLD_CHANGED,
	HARDWARE_SERVICE_BOOT_SOUND_CHANGED,
	ORGB_SERVICE_ON_BRIGHTNESS,
	ORGB_SERVICE_ON_EFFECT,
	ORGB_SERVICE_ON_COLOR,
	PROFILE_SERVICE_ON_PROFILE,
#ifdef SCX_SUPPORT
	PROFILE_SERVICE_ON_SCHEDULER,
#endif
	PROFILE_SERVICE_ON_SSD_SCHEDULER,
#ifdef STEAM_SUPPORT
	STEAM_SERVICE_GAME_EVENT,
#endif
};