#pragma once

enum class Events : int {
	APPLICATION_SHUTDOWN,
	APPLICATION_STOP,
	UDEV_CLIENT_DEVICE_EVENT,
	HARDWARE_SERVICE_USB_REMOVED,
	HARDWARE_SERVICE_USB_ADDED,
	HARDWARE_SERVICE_ON_BATTERY,
#ifdef BAT_LIMIT
	HARDWARE_SERVICE_THRESHOLD_CHANGED,
#endif
#ifdef BOOT_SOUND
	HARDWARE_SERVICE_BOOT_SOUND_CHANGED,
#endif
	ORGB_SERVICE_ON_BRIGHTNESS,
	ORGB_SERVICE_ON_EFFECT,
	ORGB_SERVICE_ON_COLOR,
	PROFILE_SERVICE_ON_PROFILE,
	PROFILE_SERVICE_ON_SCHEDULER,
	PROFILE_SERVICE_ON_SSD_SCHEDULER,
	STEAM_SERVICE_GAME_EVENT,
};